apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 909145736111.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 909145736111.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: c0159a09
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
